export declare function easeInQuad(position: number): number;
export declare function easeOutQuad(position: number): number;
export declare function easeInOutQuad(position: number): number;
export declare function easeInCubic(position: number): number;
export declare function easeOutCubic(position: number): number;
export declare function easeInOutCubic(position: number): number;
export declare function easeInQuart(position: number): number;
export declare function easeOutQuart(position: number): number;
export declare function easeInOutQuart(position: number): number;
export declare function easeInQuint(position: number): number;
export declare function easeOutQuint(position: number): number;
export declare function easeInOutQuint(position: number): number;
export declare function easeInSine(position: number): number;
export declare function easeOutSine(position: number): number;
export declare function easeInOutSine(position: number): number;
export declare function easeInExpo(position: number): number;
export declare function easeOutExpo(position: number): number;
export declare function easeInOutExpo(position: number): number;
export declare function easeInCirc(position: number): number;
export declare function easeOutCirc(position: number): number;
export declare function easeInOutCirc(position: number): number;
export declare function easeOutBounce(position: number): number;
export declare function easeInBack(position: number): number;
export declare function easeOutBack(position: number): number;
export declare function easeInOutBack(position: number): number;
export declare function elastic(position: number): number;
export declare function swingFromTo(position: number): number;
export declare function swingFrom(position: number): number;
export declare function swingTo(position: number): number;
export declare function bounce(position: number): number;
export declare function bouncePast(position: number): number;
export declare function easeFromTo(position: number): number;
export declare function easeFrom(position: number): number;
export declare function easeTo(position: number): number;
declare var _default: {
    swingFromTo: (position: number) => number;
    swingFrom: (position: number) => number;
    swingTo: (position: number) => number;
    easeFromTo: (position: number) => number;
    easeFrom: (position: number) => number;
    easeTo: (position: number) => number;
    easeInQuad: (position: number) => number;
    easeOutQuad: (position: number) => number;
    easeInOutQuad: (position: number) => number;
    easeInCubic: (position: number) => number;
    easeOutCubic: (position: number) => number;
    easeInOutCubic: (position: number) => number;
    easeInQuart: (position: number) => number;
    easeOutQuart: (position: number) => number;
    easeInOutQuart: (position: number) => number;
    easeInQuint: (position: number) => number;
    easeOutQuint: (position: number) => number;
    easeInOutQuint: (position: number) => number;
    easeInSine: (position: number) => number;
    easeOutSine: (position: number) => number;
    easeInOutSine: (position: number) => number;
    easeInExpo: (position: number) => number;
    easeOutExpo: (position: number) => number;
    easeInOutExpo: (position: number) => number;
    easeInCirc: (position: number) => number;
    easeOutCirc: (position: number) => number;
    easeInOutCirc: (position: number) => number;
    easeOutBounce: (position: number) => number;
    easeInBack: (position: number) => number;
    easeOutBack: (position: number) => number;
    easeInOutBack: (position: number) => number;
    bounce: (position: number) => number;
    bouncePast: (position: number) => number;
    elastic: (position: number) => number;
};
export default _default;
